// <auto-generated />
using System;
using ApiDigitalLesson.Migration.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiDigitalLesson.Migration.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230815194303_UpdateStudents")]
    partial class UpdateStudents
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.AboutTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("AboutTeacher");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.GroupLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCancel")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxQuantityStudents")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeacherTypeLessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TypeLessonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherTypeLessonId");

                    b.ToTable("GroupLesson");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.GroupLessonStudents", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentsId");

                    b.ToTable("GroupLessonStudents");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.Scheduler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupLessonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SingleLessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupLessonId");

                    b.HasIndex("SingleLessonId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedulers");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.SingleLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCancel")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StudentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherTypeLessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TypeLessonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentsId");

                    b.HasIndex("TeacherTypeLessonId");

                    b.ToTable("SingleLesson");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.Students", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateBirthday")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateBirthday")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.TeacherTypeLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOffline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSingle")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TypeLessonsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TypeLessonsId");

                    b.ToTable("TeacherTypeLesson");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.TypeLessons", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("TypeLessons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9"),
                            Category = 0,
                            Name = "ЕГЭ"
                        },
                        new
                        {
                            Id = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00"),
                            Category = 1,
                            Name = "ОГЭ"
                        },
                        new
                        {
                            Id = new Guid("d49844a5-2147-4dda-ad7a-12ee25b15705"),
                            Category = 2,
                            Name = "Технические науки"
                        },
                        new
                        {
                            Id = new Guid("11636f37-3044-4e6d-b78e-b88d071c043f"),
                            Category = 3,
                            Name = "Естественные науки"
                        },
                        new
                        {
                            Id = new Guid("d62aefe2-90f9-42d7-9bba-12206f58ac8e"),
                            Category = 4,
                            Name = "Гуманитарные науки"
                        },
                        new
                        {
                            Id = new Guid("0e411007-7796-4b1d-952e-19f2a00f2a7e"),
                            Category = 5,
                            Name = "Программирование"
                        },
                        new
                        {
                            Id = new Guid("2a0413ed-77d5-4229-874f-3503309121ad"),
                            Category = 6,
                            Name = "Школьная программа"
                        },
                        new
                        {
                            Id = new Guid("7f2a86d1-95a0-448f-8bae-e503cf7f9ced"),
                            Category = 7,
                            Name = "Музыка"
                        },
                        new
                        {
                            Id = new Guid("aba49ac0-e223-42d6-a72b-2734406e70af"),
                            Category = 8,
                            Name = "Искусство"
                        },
                        new
                        {
                            Id = new Guid("03f1ef6c-b12d-4698-8cef-561318d8b365"),
                            Name = "Математика (базовый уровень)",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("eb44f43e-7f12-4b52-b13b-1354ce21c6f6"),
                            Name = "Математика (профильный уровень)",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("6583af40-f7dc-4bce-bbca-08765a61ad82"),
                            Name = "Русский язык",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("0140535d-e0fe-42f3-807b-0b50722270ce"),
                            Name = "Литература",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("e568f8b8-c570-4d92-878a-893dfcfcaa62"),
                            Name = "Физика",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("57cdb5a9-5bbe-4179-bbc1-2ecdb8d2cb1e"),
                            Name = "Химия",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("8384052b-05d9-444f-aa25-a1b68e6fdd2e"),
                            Name = "История",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("1a09ca8d-3803-48e9-892f-bc060b7709d4"),
                            Name = "Обществознание",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("f48dc02b-b21e-4ecf-bc70-dba96d7a0506"),
                            Name = "Информатика",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("f8d15edd-fc07-4dc2-9168-798bb65d05c0"),
                            Name = "Биология",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("8095e947-0109-45e7-9e8a-a4947bfd0e81"),
                            Name = "География",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("300b3c18-f0d0-4ddf-97f9-2f2e1de4ef3a"),
                            Name = "Английский язык",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("2e08ea2f-0ed4-4125-bb30-264c16670482"),
                            Name = "Немецкий язык",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("c1b46ad3-c9c7-4d87-be4d-4d2845d3f8f5"),
                            Name = "Французский язык",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("35a373de-d472-4452-a545-2433126649b2"),
                            Name = "Китайский язык",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("f3ff8db8-563b-4d44-a085-62f3f1c8f155"),
                            Name = "Испанский язык",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("be7dc464-a4e8-437e-b660-1b533d24025b"),
                            Name = "География",
                            ParentId = new Guid("73d3bc41-3301-4c18-90a0-60a59cd100b9")
                        },
                        new
                        {
                            Id = new Guid("b6c08013-1e9d-487a-a590-132928fd57b8"),
                            Name = "Математика",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("5190807f-7687-495c-8b90-a4cdd87e9b0a"),
                            Name = "Русский язык",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("c5b9ed04-6fe3-4f83-b6e0-2feb84354f59"),
                            Name = "Литература",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("544e9e48-a899-4e98-bbb3-fa532fafd257"),
                            Name = "Физика",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("d722559c-6caa-48a4-a23c-a15e7fd211a3"),
                            Name = "Химия",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("f4ff7fad-cf70-4794-9144-f05a7e0c27f9"),
                            Name = "История",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("eab69696-17a5-4e03-aa2b-3187613da619"),
                            Name = "Обществознание",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("e0259c97-d02e-4c21-8370-2a450cbc8110"),
                            Name = "Информатика",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("4c83770e-7e1e-4836-b143-c7bb10e18f3a"),
                            Name = "Биология",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("1a2dfe00-a680-4588-93dd-3bc98f763789"),
                            Name = "География",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("f87b79dc-bffa-4087-8bab-ecdbef1ad7f5"),
                            Name = "Английский язык",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("f42a4000-fb65-4ca7-8f86-18eac4602324"),
                            Name = "Немецкий язык",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("9c06eedd-0c30-45c5-a3c8-34bd8b166dbe"),
                            Name = "Французский язык",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("67dd1094-d12e-42ea-a3df-840933dae46f"),
                            Name = "Китайский язык",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("5f23d83d-14f9-475f-b58d-006f9ab58fc5"),
                            Name = "Испанский язык",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("e16392a5-f081-4142-ad6f-11f81f7dfbdb"),
                            Name = "География",
                            ParentId = new Guid("02c742a7-ac20-4b5b-9e01-b29d9ac30a00")
                        },
                        new
                        {
                            Id = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4"),
                            Name = "1-4 класс",
                            ParentId = new Guid("2a0413ed-77d5-4229-874f-3503309121ad")
                        },
                        new
                        {
                            Id = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb"),
                            Name = "5-9 класс",
                            ParentId = new Guid("2a0413ed-77d5-4229-874f-3503309121ad")
                        },
                        new
                        {
                            Id = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b"),
                            Name = "9-11 класс",
                            ParentId = new Guid("2a0413ed-77d5-4229-874f-3503309121ad")
                        },
                        new
                        {
                            Id = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554"),
                            Name = "Народные языки",
                            ParentId = new Guid("2a0413ed-77d5-4229-874f-3503309121ad")
                        },
                        new
                        {
                            Id = new Guid("0e931dbc-97dd-4bd4-a28c-9771611fda06"),
                            Name = "Русский язык",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("557f97be-dbb5-448e-8e5a-e8a0415e4a65"),
                            Name = "Литературное чтение",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("234e21cd-413f-44ab-b265-26343c8756ed"),
                            Name = "Математика",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("73bff5da-d675-4a45-9a4d-120140a17169"),
                            Name = "Обществознание",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("13ecbb8d-448e-4437-90bd-1cdb44ddee63"),
                            Name = "Окружающий мир",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("650a1156-75ab-4698-8ed6-d051e592c49b"),
                            Name = "ИЗО",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("a4943884-1701-4fbb-97d2-293d2ff09abc"),
                            Name = "Музыка",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("3d10ff02-bf73-45f2-8716-28b4164dba5d"),
                            Name = "Технология",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("6167efd6-7146-46eb-937c-6c4ca0e41f36"),
                            Name = "Физическая культура",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("357c7d39-cfdd-46c5-8a41-3b7645e2e18d"),
                            Name = "Английский язык",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("647b8fab-5e46-44ca-b062-5b88cd3001e7"),
                            Name = "Немецкий язык",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("63598131-0061-44b4-b5ea-e1ceb5e11574"),
                            Name = "Французский язык",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("ca29cbd6-b7f2-4643-a061-59442ed06bdf"),
                            Name = "Испанский язык",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("08a2ab57-d531-4d38-8b11-9fe85583392d"),
                            Name = "Китайский язык",
                            ParentId = new Guid("328b33f2-1f47-4f97-93d4-944c7c9105a4")
                        },
                        new
                        {
                            Id = new Guid("5b91b966-5640-417f-bafd-5afb0e06d271"),
                            Name = "Русский язык",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("2d1153c4-7082-4d98-ae4b-bebd11c23b62"),
                            Name = "Литература",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("f044c84c-c9c8-48a5-b26c-91aaeff14e69"),
                            Name = "История",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("37205ae7-c913-4ac4-baf1-a5c2ddcb51dd"),
                            Name = "Обществознание",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("db9e94e0-85f9-4061-aef9-957b1056eb49"),
                            Name = "География",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("cbfe308f-ed4e-4a46-b2a5-138d2ef84c65"),
                            Name = "Алгебра",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("cd861553-a73b-4b8c-bd00-73c3e691d19d"),
                            Name = "Геометрия",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("ad807089-66a8-4252-a4b0-071e6b5fb70d"),
                            Name = "Информатика",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("e672754d-f452-43d7-993f-6ede7be2ffa7"),
                            Name = "Основы духовно-нравственной культуры народов России",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("33b44162-2578-4558-8d89-6bb17a044b7c"),
                            Name = "Основы религиозных культур и светской этики",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("9c2dcb5c-438b-485f-9192-293e51580214"),
                            Name = "Физика",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("f07b79fe-c1f7-496e-8db1-e4687fcb809d"),
                            Name = "Биология",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("60a78f8e-5788-4cc9-9101-12d6018cf45c"),
                            Name = "Химия",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("9c610d8b-9f65-4d17-8b14-c91a5d58a7f3"),
                            Name = "Изобразительное искусство",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("e6f3ac62-a1df-47c1-bf23-e89110261e49"),
                            Name = "Музыка",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("cf6f0fb1-2b34-48e9-8026-93f00fcde4cb"),
                            Name = "Технология",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("419dbbce-004b-49be-badc-b25fe68fe409"),
                            Name = "Физическая культура",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("16ef42fe-cd23-474b-b637-88fd85cdd685"),
                            Name = "Основы безопасности жизнедеятельности",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("11bd2795-b5e0-404e-9102-9e70d5bbdb81"),
                            Name = "Английский язык",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("486f0c7c-4c97-44a1-8af2-af1fe3a542d3"),
                            Name = "Немецкий язык",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("ce743ed9-5c2f-47c3-b975-09d5f7eafe63"),
                            Name = "Французский язык",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("606e1c55-372e-4e98-87bf-74ef6c6fd6ea"),
                            Name = "Испанский язык",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("1f9cef09-41f7-4b79-86a5-b40dc4132980"),
                            Name = "Китайский язык",
                            ParentId = new Guid("e64bdaa8-4587-4a2e-b016-87868b8994bb")
                        },
                        new
                        {
                            Id = new Guid("af35f247-2290-405e-8b18-d3b831f4609a"),
                            Name = "Алгебра",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("d4ec6d54-9176-4207-8d48-8be42f1b5c4e"),
                            Name = "Геометрия",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("b755e154-af8c-4830-ad69-7a140e7aa9a7"),
                            Name = "Русский язык",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("f0f34558-dbd5-41dc-9d31-74112fcfd179"),
                            Name = "Литература",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("b9fee7b3-b089-4fde-8865-50f22c326e41"),
                            Name = "Всеобщая история",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("311a9ffd-9188-4f7a-b4ff-7d47bceb513f"),
                            Name = "История России",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("ea4527e4-2842-4503-b24f-438d0e8c98ec"),
                            Name = "Обществознание",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("876143d7-80ce-4c58-95d1-9d4004f08c59"),
                            Name = "Черчение",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("7f2e747d-d039-4529-92b9-d700cd05ab1c"),
                            Name = "Основы безопасности и жизнедеятельности",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("f318d56d-9944-43a5-bd51-446a27f9cd7c"),
                            Name = "Информатика",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("ea7f91d7-c53e-4817-904f-3e5bf2196bf5"),
                            Name = "География",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("7a5bddf1-0caf-40b6-8a45-a4454da939aa"),
                            Name = "Физическая культура",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("c1f709b9-a8b7-4ea6-bac0-86a6f25a2626"),
                            Name = "Биология",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("a3ad31f7-d920-434c-8b91-5ef8592d7181"),
                            Name = "Физика",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("dcf1b823-1442-45fa-94a1-a7704d464ce1"),
                            Name = "Химия",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("333da743-ff45-45b5-b7a8-d86923262fac"),
                            Name = "Английский язык",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("e1e7fc8d-b14d-4158-a3f6-a59b10d152fe"),
                            Name = "Немецкий язык",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("7ef4e280-56df-4d84-b3d8-2dba5463ac48"),
                            Name = "Французский язык",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("b185fc5c-809d-4a2e-9c3e-f7253239fc23"),
                            Name = "Испанский язык",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("dd3005c7-da3d-4478-bd80-8137e4289c00"),
                            Name = "Китайский язык",
                            ParentId = new Guid("c7176667-421c-4fe9-bc8d-5bbccac79d7b")
                        },
                        new
                        {
                            Id = new Guid("dd2cb987-d1b0-4e17-8714-8f6e70e113f7"),
                            Name = "Абазинский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("a8a8dd05-1197-45d8-8b4d-bd5816496662"),
                            Name = "Адыгейский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("44a2a02e-de32-4cdf-87cb-49d4e0e634c0"),
                            Name = "Алтайский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("55f4135d-03be-4ef7-9ac7-1fa5b6622d75"),
                            Name = "Башкирский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("f915094f-c1bd-4ae8-9deb-d58fd42c424a"),
                            Name = "Бурятский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("5c4bad45-acd6-42a8-bbb6-1d7a9d2f0f6f"),
                            Name = "Дагестанский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("9eee743c-0782-4b53-aa4b-f1a606fb8ff1"),
                            Name = "Ингушский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("29c9952e-ff3b-42a4-a049-94276250e91a"),
                            Name = "Кабардино-черкесский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("26db8bfb-4e17-46f1-b384-f91906337e5f"),
                            Name = "Калмыцкий язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("31242b82-8c03-4f70-8dfc-b7c703435557"),
                            Name = "Карачаево-балкарский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("03024a42-ae7a-498c-8bd7-cb03cc99a239"),
                            Name = "Коми язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("5e13d24c-5e38-467a-a000-90177ddebf25"),
                            Name = "Крымскотатарский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("72207587-e3d8-4230-9c5f-f8c88a9919a1"),
                            Name = "Марийский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("d192db8f-8020-46e3-aa83-bcd199851af3"),
                            Name = "Мокшанский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("cad31653-9d92-42f5-b365-1b7c74c60e2e"),
                            Name = "Ногайский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("5e17a0ae-0810-4e87-90c8-57811d3626d3"),
                            Name = "Осетинский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("0ccaf83b-1986-444c-8558-c7a881094133"),
                            Name = "Татарский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("64dcc962-8ae2-45c1-a50e-6b15e5ff62d7"),
                            Name = "Тувинский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("31952475-e36b-4f5c-a3ec-572b22de8f1c"),
                            Name = "Удмуртский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("8e9fac02-d23e-4aa5-906d-c065bb48ec68"),
                            Name = "Хакасский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("de550add-938a-4438-8e37-cf18f3faa4f5"),
                            Name = "Чеченский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("d48f70f3-9275-404c-9526-36f6854a67f6"),
                            Name = "Чувашский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("530c2fcc-26d5-4a4e-961b-a87f73f5d8ef"),
                            Name = "Эрзянский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        },
                        new
                        {
                            Id = new Guid("41ebb78b-05f7-4133-be05-b079ff75f707"),
                            Name = "Якутский язык",
                            ParentId = new Guid("fb052d9b-c138-4822-b1d8-8473105e0554")
                        });
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.AboutTeacher", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.GroupLesson", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.TeacherTypeLesson", "TeacherTypeLesson")
                        .WithMany()
                        .HasForeignKey("TeacherTypeLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherTypeLesson");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.GroupLessonStudents", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.GroupLesson", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspDigitalLesson.Model.Entity.Students", "Students")
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.Scheduler", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.GroupLesson", "GroupLesson")
                        .WithMany()
                        .HasForeignKey("GroupLessonId");

                    b.HasOne("AspDigitalLesson.Model.Entity.SingleLesson", "SingleLesson")
                        .WithMany()
                        .HasForeignKey("SingleLessonId");

                    b.HasOne("AspDigitalLesson.Model.Entity.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupLesson");

                    b.Navigation("SingleLesson");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.SingleLesson", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.Students", "Students")
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspDigitalLesson.Model.Entity.TeacherTypeLesson", "TeacherTypeLesson")
                        .WithMany()
                        .HasForeignKey("TeacherTypeLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Students");

                    b.Navigation("TeacherTypeLesson");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.TeacherTypeLesson", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspDigitalLesson.Model.Entity.TypeLessons", "TypeLessons")
                        .WithMany()
                        .HasForeignKey("TypeLessonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");

                    b.Navigation("TypeLessons");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.TypeLessons", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.TypeLessons", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.TypeLessons", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
