// <auto-generated />
using System;
using ApiDigitalLesson.Migration.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiDigitalLesson.Migration.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230815193843_UpdateTypeLesson")]
    partial class UpdateTypeLesson
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.AboutTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("AboutTeacher");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.GroupLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCancel")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxQuantityStudents")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeacherTypeLessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TypeLessonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherTypeLessonId");

                    b.ToTable("GroupLesson");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.GroupLessonStudents", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentsId");

                    b.ToTable("GroupLessonStudents");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.Scheduler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupLessonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SingleLessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupLessonId");

                    b.HasIndex("SingleLessonId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedulers");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.SingleLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCancel")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StudentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeacherTypeLessonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TypeLessonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentsId");

                    b.HasIndex("TeacherTypeLessonId");

                    b.ToTable("SingleLesson");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.Students", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateBirthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateBirthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("bytea");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Teacher");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.TeacherTypeLesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGroup")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOffline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSingle")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TypeLessonsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TypeLessonsId");

                    b.ToTable("TeacherTypeLesson");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.TypeLessons", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("TypeLessons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c"),
                            Category = 0,
                            Name = "ЕГЭ"
                        },
                        new
                        {
                            Id = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6"),
                            Category = 1,
                            Name = "ОГЭ"
                        },
                        new
                        {
                            Id = new Guid("b0c91cec-2ec5-4f3f-a960-52abac865a18"),
                            Category = 2,
                            Name = "Технические науки"
                        },
                        new
                        {
                            Id = new Guid("b2ba1190-494a-40ff-9b8c-082bd57a94a3"),
                            Category = 3,
                            Name = "Естественные науки"
                        },
                        new
                        {
                            Id = new Guid("79eadd98-13b6-46c1-9841-530197508851"),
                            Category = 4,
                            Name = "Гуманитарные науки"
                        },
                        new
                        {
                            Id = new Guid("75abf26f-79fc-4d09-b6a5-e793ca2e717b"),
                            Category = 5,
                            Name = "Программирование"
                        },
                        new
                        {
                            Id = new Guid("a774cfab-41b7-459c-bde9-d13a63bb4cac"),
                            Category = 6,
                            Name = "Школьная программа"
                        },
                        new
                        {
                            Id = new Guid("63d16c9b-4d4f-4f17-9fff-339822b9e020"),
                            Category = 7,
                            Name = "Музыка"
                        },
                        new
                        {
                            Id = new Guid("607036e2-4345-4803-b4ab-3da8209e11b5"),
                            Category = 8,
                            Name = "Искусство"
                        },
                        new
                        {
                            Id = new Guid("e1da3c8d-16f5-4fb5-99a4-ba68bd99d455"),
                            Name = "Математика (базовый уровень)",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("eb51d6b0-915c-4908-9cbe-abd76ae36208"),
                            Name = "Математика (профильный уровень)",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("4c9871c4-bb1c-42f0-a172-fe4b7ec1d3c4"),
                            Name = "Русский язык",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("8c52b1a6-199d-4a08-ad38-1ad3c9458580"),
                            Name = "Литература",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("7ee60d2a-f2ec-46fb-b350-efdf0947dc08"),
                            Name = "Физика",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("239c3b96-ea83-426c-ae47-25067c3ddc24"),
                            Name = "Химия",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("531a83fc-e264-4d55-aa50-48cfe20650cc"),
                            Name = "История",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("5dee1b23-3b1c-4532-82ae-84df497f2aeb"),
                            Name = "Обществознание",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("c59488e2-c78c-4c6b-aaba-5cb4a2f10136"),
                            Name = "Информатика",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("1a9ebfe5-f369-4003-a685-3a8a950f5f90"),
                            Name = "Биология",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("3be88df0-004f-4021-bd7e-91a6833717d6"),
                            Name = "География",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("d3da337a-5769-497b-a220-c924d553ce7f"),
                            Name = "Английский язык",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("496e50f0-dc23-48f4-8c42-7cf21a62e31f"),
                            Name = "Немецкий язык",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("e7f98aec-b6f6-4820-b684-030030dc104d"),
                            Name = "Французский язык",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("f1aba6ee-2f8d-4832-91b9-7026cc753517"),
                            Name = "Китайский язык",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("d6071be5-efe4-4dd1-8169-8062cffcb394"),
                            Name = "Испанский язык",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("2fc9fa79-345e-42a0-a4a5-4099d4c9a7ab"),
                            Name = "География",
                            ParentId = new Guid("5ca3bf2d-14aa-469c-bc97-7616ebb6c53c")
                        },
                        new
                        {
                            Id = new Guid("ffbea81b-2c82-4901-9cf9-829c5a847303"),
                            Name = "Математика",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("ae84f8d8-6192-4c51-b8fe-c1a254cc5d21"),
                            Name = "Русский язык",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("f3da9de4-5623-4af5-82fa-8b502cd88439"),
                            Name = "Литература",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("1cbdca8a-34ae-4330-85be-51f537b5852d"),
                            Name = "Физика",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("5c8cc70e-9a12-4b61-8d87-457285c39975"),
                            Name = "Химия",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("b4a73517-2973-46e9-aa0d-9dee26eb7cfb"),
                            Name = "История",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("1d620d00-96bd-47e8-a474-b973073daacc"),
                            Name = "Обществознание",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("e31ae3b9-4f59-4907-8444-18cb0502f19f"),
                            Name = "Информатика",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("64be8997-73ef-4435-a448-bb8bfd56f249"),
                            Name = "Биология",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("eb90c123-9f0e-4c94-a355-84a7d89a9531"),
                            Name = "География",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("b77ab478-d751-46f3-87b4-6d04dc46cb22"),
                            Name = "Английский язык",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("034ed3ac-5b71-4d7f-bb05-1c5fcca3f3f3"),
                            Name = "Немецкий язык",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("c0f07876-952f-4219-a1c7-7b8e0065b28f"),
                            Name = "Французский язык",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("877593f2-06c5-4db3-ab9d-231730386853"),
                            Name = "Китайский язык",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("c30bd026-8ac6-4266-80ee-0a50fb5a605c"),
                            Name = "Испанский язык",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("f3fedbaf-42e5-4718-b6c9-7f6358d2b3f2"),
                            Name = "География",
                            ParentId = new Guid("6d8f3b3d-9aec-4f1b-a140-765af0dd0da6")
                        },
                        new
                        {
                            Id = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96"),
                            Name = "1-4 класс",
                            ParentId = new Guid("a774cfab-41b7-459c-bde9-d13a63bb4cac")
                        },
                        new
                        {
                            Id = new Guid("b5da659d-09c2-466f-94df-452331c5da52"),
                            Name = "5-9 класс",
                            ParentId = new Guid("a774cfab-41b7-459c-bde9-d13a63bb4cac")
                        },
                        new
                        {
                            Id = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb"),
                            Name = "9-11 класс",
                            ParentId = new Guid("a774cfab-41b7-459c-bde9-d13a63bb4cac")
                        },
                        new
                        {
                            Id = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1"),
                            Name = "Народные языки",
                            ParentId = new Guid("a774cfab-41b7-459c-bde9-d13a63bb4cac")
                        },
                        new
                        {
                            Id = new Guid("a1bd041c-1958-4ce8-b7fc-9b076fab0c9b"),
                            Name = "Русский язык",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("8a2d0eea-13d5-495a-a6b5-8439f9d0d264"),
                            Name = "Литературное чтение",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("35de43b1-6fc3-4767-867b-2ab38d30c391"),
                            Name = "Математика",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("409a29a8-c568-4433-b310-7856531ab9ee"),
                            Name = "Обществознание",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("22c2ca72-f2a5-4ea9-b67f-7713a09f7d40"),
                            Name = "Окружающий мир",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("3683b36e-7256-4c15-9e86-f10cde543ddb"),
                            Name = "ИЗО",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("a961d399-9c50-4511-8aa3-64af8d457f47"),
                            Name = "Музыка",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("29354732-ff26-4285-b924-63ad07276f32"),
                            Name = "Технология",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("213dbfbf-7ec5-4d79-af7a-d830437cc1c7"),
                            Name = "Физическая культура",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("f4fb3536-0aba-49ec-a9d2-485181e808eb"),
                            Name = "Английский язык",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("781c9704-b48b-4fa1-86f2-18973326f95d"),
                            Name = "Немецкий язык",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("489352bd-ace8-4c00-ba8b-110f0477633a"),
                            Name = "Французский язык",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("2c56f648-da59-49a2-8bae-975a2e85c3a7"),
                            Name = "Испанский язык",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("114318a0-d94b-4771-a176-e356438bc225"),
                            Name = "Китайский язык",
                            ParentId = new Guid("9d497662-5e13-483f-bc87-c91b2368fe96")
                        },
                        new
                        {
                            Id = new Guid("8ef0f6bb-3f3d-4b2f-8126-8c50755bacff"),
                            Name = "Русский язык",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("6f77f84d-63f2-4e53-b7de-c643d8c74d9a"),
                            Name = "Литература",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("3b6b7fbd-7f04-40dd-8084-55a8bea9037e"),
                            Name = "История",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("fea4caf1-42c8-45f5-b317-3f168ed36806"),
                            Name = "Обществознание",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("9668f6b3-327e-4609-ab7d-76f3a92b8be5"),
                            Name = "География",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("1dcb97a1-417a-4189-aa22-5276c89fc2ca"),
                            Name = "Алгебра",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("558866fc-d66d-4ec8-a837-4c795c08a90f"),
                            Name = "Геометрия",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("0b8d1162-455a-47e3-8441-e7cf3972957c"),
                            Name = "Информатика",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("9f33bc61-4a9a-4b50-8e5c-eebdc82c3916"),
                            Name = "Основы духовно-нравственной культуры народов России",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("2576d6b3-3ad3-4f7f-81be-ce7778f08b3f"),
                            Name = "Основы религиозных культур и светской этики",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("e38b2585-7bea-4098-8528-8c3ece2de672"),
                            Name = "Физика",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("dc643621-f6e4-4aec-9f92-731a6e23a7d7"),
                            Name = "Биология",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("5e0011bc-a244-4b65-9d11-da3c3b447696"),
                            Name = "Химия",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("c9c311f8-9a40-4fbf-b24f-5c9cb6c540e3"),
                            Name = "Изобразительное искусство",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("52a7fa84-1d40-466c-bae3-8c859cfb1b44"),
                            Name = "Музыка",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("7accb67b-52c9-46b1-a1d5-f135412591ad"),
                            Name = "Технология",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("0312024c-d57c-458a-a06c-248daf1abd7b"),
                            Name = "Физическая культура",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("3b49c066-ad47-4a28-b6e0-c896dc126e50"),
                            Name = "Основы безопасности жизнедеятельности",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("4d7ff7de-3a98-4d90-b15e-459133179674"),
                            Name = "Английский язык",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("07757568-ba24-4ba6-9802-b5593a9e6506"),
                            Name = "Немецкий язык",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("1832f7bf-85f5-4f11-bbc4-a96635602de5"),
                            Name = "Французский язык",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("982608d3-dba8-4b56-ab19-7a235d73c58e"),
                            Name = "Испанский язык",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("b215ba67-19d3-4121-9af2-5b54e6bcc3fc"),
                            Name = "Китайский язык",
                            ParentId = new Guid("b5da659d-09c2-466f-94df-452331c5da52")
                        },
                        new
                        {
                            Id = new Guid("40a47c2a-3503-4fc3-a2f6-54baa9ed7c64"),
                            Name = "Алгебра",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("c9bf63b2-88c9-4c2d-8e2f-b519d469f1bd"),
                            Name = "Геометрия",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("83f4e8e2-786a-41b5-97a3-68eb50353a81"),
                            Name = "Русский язык",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("b0e29471-50b5-473e-8752-730b8f3e1d9b"),
                            Name = "Литература",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("0adb8432-6131-4385-9fcb-c41c07f103a8"),
                            Name = "Всеобщая история",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("1176275a-7c04-4c99-a1b9-74ff4b4a930c"),
                            Name = "История России",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("d29accbf-51f0-4310-9def-f5372ff40d46"),
                            Name = "Обществознание",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("5263212b-7e84-442d-b625-d86d50aed9a1"),
                            Name = "Черчение",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("a5ddf92d-0f5e-46ab-9aba-c4f8e8c7a8fc"),
                            Name = "Основы безопасности и жизнедеятельности",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("5c480931-3847-413f-aa7a-3bfeac4cb204"),
                            Name = "Информатика",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("6164dd71-a17d-489f-82f5-8a48bffd9682"),
                            Name = "География",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("23d44660-7ea0-416b-8f9b-f1d04222e74f"),
                            Name = "Физическая культура",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("ab5721ff-8e7e-4845-bca2-eb4d9cc760db"),
                            Name = "Биология",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("e270072c-95bc-4b78-932a-4e411b61dcb8"),
                            Name = "Физика",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("4b37231f-48a2-40dd-8f48-d6db63251b16"),
                            Name = "Химия",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("cd341d95-891b-49df-9d36-8ac87c68ee58"),
                            Name = "Английский язык",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("a7674261-0973-4d6c-87c5-a437ccadab73"),
                            Name = "Немецкий язык",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("1c784137-969d-4029-bcd4-84e602c9c595"),
                            Name = "Французский язык",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("345ae51e-a805-4fad-9034-1795d3c4dd64"),
                            Name = "Испанский язык",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("4a239ae1-fdbf-4f43-a66b-66429ac744ed"),
                            Name = "Китайский язык",
                            ParentId = new Guid("d6d6b75d-3aab-473f-82f8-d9eb904ce2cb")
                        },
                        new
                        {
                            Id = new Guid("2c4074d7-e64c-40c0-b81f-b37b0bb95a24"),
                            Name = "Абазинский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("037a19e4-5c3f-42e2-909e-9879fb5c9c3a"),
                            Name = "Адыгейский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("b94275af-eaf7-4d9a-9704-2dd5ea9e5f34"),
                            Name = "Алтайский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("742ec983-4e4b-4e50-beb8-1a2b988a52e4"),
                            Name = "Башкирский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("e457c58e-53bf-4031-b5e8-685d9f579209"),
                            Name = "Бурятский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("b8324891-99f3-4a31-86b9-4f4e31742ef6"),
                            Name = "Дагестанский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("ed3a605d-c4ea-4f6e-9490-5336f35224b9"),
                            Name = "Ингушский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("80bc2180-aceb-43e6-b2ee-60068895ad6d"),
                            Name = "Кабардино-черкесский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("bd5a6891-f713-4e34-b193-fd039b89a31b"),
                            Name = "Калмыцкий язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("4d0c622e-6828-4e1f-bc81-66081df9931e"),
                            Name = "Карачаево-балкарский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("4f3ab9a2-d65c-41eb-9ad9-8d27fd8b3724"),
                            Name = "Коми язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("226a79a7-c8ec-41c6-8658-b58798347e7a"),
                            Name = "Крымскотатарский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("cb7e0a0e-d98e-48ad-9414-cdc476118e07"),
                            Name = "Марийский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("8ad9a40f-c15a-4d31-83c6-8b7fe1c0f53e"),
                            Name = "Мокшанский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("ce9ce68e-e924-4d3c-8c43-1aaac8071193"),
                            Name = "Ногайский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("a74cbad2-0923-4e2b-8a85-383f83050bd1"),
                            Name = "Осетинский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("f8138674-c66d-4a8c-86d5-a04243c48d22"),
                            Name = "Татарский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("f863b7c3-cd33-413a-93b1-25d2506f6d91"),
                            Name = "Тувинский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("7cc383f3-23e8-4c01-9f2e-c9418d0712ec"),
                            Name = "Удмуртский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("6de19be2-7712-49c8-ab5f-2d55d5256620"),
                            Name = "Хакасский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("c4cff784-d33f-4457-915e-551725484400"),
                            Name = "Чеченский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("997b6d7f-64b4-4160-b9dc-6fef6fedfd3c"),
                            Name = "Чувашский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("c5f1cd37-4eba-4265-a16b-31e1093850d7"),
                            Name = "Эрзянский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        },
                        new
                        {
                            Id = new Guid("828a4622-d043-4ce5-a06c-aba564e4c589"),
                            Name = "Якутский язык",
                            ParentId = new Guid("73d44fd1-ef69-48e0-9a29-654237b395b1")
                        });
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.AboutTeacher", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.GroupLesson", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.TeacherTypeLesson", "TeacherTypeLesson")
                        .WithMany()
                        .HasForeignKey("TeacherTypeLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeacherTypeLesson");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.GroupLessonStudents", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.GroupLesson", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspDigitalLesson.Model.Entity.Students", "Students")
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.Scheduler", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.GroupLesson", "GroupLesson")
                        .WithMany()
                        .HasForeignKey("GroupLessonId");

                    b.HasOne("AspDigitalLesson.Model.Entity.SingleLesson", "SingleLesson")
                        .WithMany()
                        .HasForeignKey("SingleLessonId");

                    b.HasOne("AspDigitalLesson.Model.Entity.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupLesson");

                    b.Navigation("SingleLesson");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.SingleLesson", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.Students", "Students")
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspDigitalLesson.Model.Entity.TeacherTypeLesson", "TeacherTypeLesson")
                        .WithMany()
                        .HasForeignKey("TeacherTypeLessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Students");

                    b.Navigation("TeacherTypeLesson");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.TeacherTypeLesson", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspDigitalLesson.Model.Entity.TypeLessons", "TypeLessons")
                        .WithMany()
                        .HasForeignKey("TypeLessonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");

                    b.Navigation("TypeLessons");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.TypeLessons", b =>
                {
                    b.HasOne("AspDigitalLesson.Model.Entity.TypeLessons", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AspDigitalLesson.Model.Entity.TypeLessons", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
